version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  pre_build:
    commands:
      - echo Running lint...
      - npm run lint

  build:
    commands:
      - echo Running tests...
      - npm test

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - "**/*"
  discard-paths: no
